apiVersion: v1
kind: ConfigMap
metadata:
  name: mlops-aws-poc-api-config
  namespace: mlops-aws-poc
  labels:
    app.kubernetes.io/name: mlops-aws-poc-api
    app.kubernetes.io/part-of: mlops-aws-poc
data:
  APP_HOST: "0.0.0.0"
  APP_PORT: "8000"
  MODEL_PATH: "/models/model.joblib"
  MODEL_METADATA_PATH: "models/registry/baseline_regressor_v1.json"
